lab03/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'

urlpatterns = [
    path('', views.home, name='home'),
    path('encuesta/', views.index,name='index'),
    path('encuesta/<int:pregunta_id>/',views.detalle,name='detalle'),
    path('encuesta/<int:pregunta_id>/votar',views.votar,name='votar'),
    path('votos/', views.votos, name='votos')
]

lab03/lab03/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('encuesta.urls')),
]

lab03/encuesta/models.py
from django.db import models

# Create your models here.
class Pregunta(models.Model):
    pregunta_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

lab03/encuesta/views.py
from django.shortcuts import render
from .models import Opcion, Pregunta

def home(request):
    return render(request, 'main.html')

# Create your views here.
def index(request):
    latest_question_list = Pregunta.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list':latest_question_list
    }
    return render(request,'encuesta/index.html',context)

def detalle(request,pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    context = {
        'pregunta':pregunta
    }
    
    return render(request,'encuesta/detalle.html',context)

def votar(request,pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    opcionSeleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    opcionSeleccionada.votos += 1
    opcionSeleccionada.save()
    context = {
        'pregunta':pregunta
    }
    return render(request,'encuesta/resultados.html',context)

def votos(request):
    pregunta1 = Pregunta.objects.get(pk=1)
    pregunta2 = Pregunta.objects.get(pk=2)
    #opcionSeleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    context = {
        'pregunta1':pregunta1,
        'pregunta2':pregunta2
    }
    return render(request, 'encuesta/votos.html', context)

lab03/encuesta/templates/encuesta/detalle.html
{% extends "main.html" %}
{% load static %}
{% block main %}
<div class="container-img">
    <img src="{% static 'img/encuesta.jpeg' %}" alt="">
</div>
<h1>OPCIONES</h1>
<hr style="margin-top: 10px;">
<h2>PREGUNTA</h2>
<h2>{{ pregunta.pregunta_text }}</h2>
<div class="lab">
    <form action="{% url 'encuesta:votar' pregunta.id %}" method="post">
        {% csrf_token %}
        {% for opcion in pregunta.opcion_set.all %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id}}" required>
        <label for="opcion{{forloop.counter }}">{{ opcion.opcion_texto }}</label><br>
        {% endfor %}
        <input class="btn" type="submit" value="votar">
    </form>
    <button><a href="{% url 'encuesta:index' %}">Ver Preguntas</a></button>
    
</div>

{% endblock %}

lab03/encuesta/templates/encuesta/index.html
{% extends "main.html" %}
{% load static %}
{% block main %}
<div class="container-img">
    <img src="{% static 'img/option.jpeg' %}" alt="">
</div>
<h1>ENCUESTA</h1>
<hr style="margin-top: 10px;">
<h2>PREGUNTAS</h2>
<div class="lab">
    <h2>{% if latest_question_list %}
        <ul>
            {% for pregunta in latest_question_list %}
            <li>
                <a href="/encuesta/{{pregunta.id}}">
                    {{pregunta.pregunta_text}}
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No hay registros</p>
        {% endif %}
    </h2>
</div>

{% endblock %}

lab03/encuesta/templates/encuesta/resultados.html
{% extends "main.html" %}
{% load static %}
{% block main %}
<div class="container-img">
    <img src="{% static 'img/voto.jpeg' %}" alt="">
</div>
<h1>VOTOS</h1>
<hr style="margin-top: 10px;">
<h2>PREGUNTA</h2>
<h2>{{ pregunta.pregunta_text }}</h2>
<div class="lab">
    <ul>
        {%for opcion in pregunta.opcion_set.all %}
            <li class="list">{{opcion.opcion_texto }}  <i class="fa-solid fa-arrow-right">  </i>  {{opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
        {% endfor %}
    </ul>

    <button class="btnvotos"><a href="{% url 'encuesta:detalle' pregunta.id %}">Votar de nuevo</a></button><br>
    <button class="btnvotos"><a href="{% url 'encuesta:index' %}">Ver Preguntas</a></button>
    
</div>

{% endblock %}

lab03/encuesta/templates/encuesta/votos.html
{% extends "main.html" %}
{% load static %}
{% block main %}
<div class="container-img">
    <img src="{% static 'img/voto.jpeg' %}" alt="">
</div>
<h1>VOTOS</h1>
<hr style="margin-top: 10px;">
<h2>PREGUNTA 1</h2>
<hr>
<h2>{{ pregunta1.pregunta_text }}</h2>
<div class="lab">
    <ul>
        {%for opcion1 in pregunta1.opcion_set.all %}
            <li class="list">{{opcion1.opcion_texto }}  <i class="fa-solid fa-arrow-right">  </i>  {{opcion1.votos }} voto{{ opcion1.votos|pluralize }}</li>
        {% endfor %}
    </ul>
    
</div>
<hr>
<h2>PREGUNTA 2</h2>
<hr>
<h2>{{ pregunta2.pregunta_text }}</h2>
<div class="lab">
    <ul>
        {%for opcion2 in pregunta2.opcion_set.all %}
            <li class="list">{{opcion2.opcion_texto }}  <i class="fa-solid fa-arrow-right">  </i>  {{opcion2.votos }} voto{{ opcion1.votos|pluralize }}</li>
        {% endfor %}
    </ul>
    
</div>

{% endblock %}

lab03/encuesta/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Lab - 03</title>
</head>

<body>
    <!-- HEADER -->
    <div class="container-header">
        <header>
            <div class="logo">
                <a href="#">QJ Developer</a>
            </div>
            <nav id="nav">
                <ul>
                    <li><a href="/" onclick="seleccionar()"><i class="fa-solid fa-house"></i> INICIO</a></li>
                    <li><a href="/encuesta" onclick="seleccionar()"><i class="fa-solid fa-question"></i> PREGUNTAS</a></li>
                    <li><a href="/votos" onclick="seleccionar()"><i class="fa-solid fa-check-to-slot"></i> VOTOS</a></li>
                </ul>
            </nav>
            <div class="nav-responsive" onclick="mostrarOcultarMenu()">
                <i class="fa-solid fa-bars"></i>
            </div>
        </header>
    </div>

    <!-- ------MAIN---------->
    <section id="home" class="home">
        <div class="content-banner">
            {% block main %}
            <div class="container-img">
                <img src="{% static 'img/foto.jpg' %}" alt="">
            </div>
            <h1>FREDDY QUEA</h1>
            <h2>DESARROLLO DE APLICACIONES EMPRESARIALES</h2>
            <div class="lab">
                <h2>LABORATORIO - 03</h2>
            </div>
            {% endblock %}
        </div>
    </section>

    <!-- footer -->
    <footer>
        <a href="#home" class="arriba">
            <i class="fa-solid fa-angles-up"></i>
        </a>
        <div class="redes">
            <a href="#"><i class="fa-brands fa-facebook-f"></i></a>
            <a href="#"><i class="fa-brands fa-instagram"></i></a>
            <a href="#"><i class="fa-brands fa-github"></i></a>
            <a href="#"><i class="fa-brands fa-discord"></i></a>
        </div>
    </footer>

    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>